update: website

diff --git a/.github/workflows/release.yaml b/.github/workflows/release.yaml
--- a/.github/workflows/release.yaml
+++ b/.github/workflows/release.yaml
@@ -1,18 +1,14 @@
-name: 🚀 release to github pages
+name: 🚀 full release deployment
 on:
   push:
     branches: ["release"]
-
-  # Allows you to run this workflow manually from the Actions tab
   workflow_dispatch:
 
-# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
 permissions:
   contents: read
   pages: write
   id-token: write
 
-# Allow one concurrent deployment
 concurrency:
   group: "pages"
   cancel-in-progress: true
@@ -24,45 +20,38 @@ jobs:
       url: ${{ steps.deployment.outputs.page_url }}
     runs-on: ubuntu-latest
     steps:
+      - uses: actions/checkout@v4
 
-    - name: 🔔 checkout
-      uses: actions/checkout@v3
+      - uses: actions/configure-pages@v5
 
-    - name: 🔧 setup node
-      uses: actions/setup-node@v3
-      with:
-        node-version: '18'
+      - uses: actions/setup-node@v4
+        with:
+          node-version: "22"
 
-    - name: 📦 install dependencies
-      run: npm ci
+      - run: npm ci
+      - run: npm run build -s
+      - run: npm test
 
-    - name: 🔨 build
-      run: npm run build-production
+      - name: 🗑️ delete dev symlinks (robust)
+        run: |
+          # Remove dev folders if they exist; won't fail if missing
+          rm -rf x/node_modules x/s x/assets || true
 
-    - name: 🚚 tracking ignored stuff
-      run: |
-        sed -i.bak -e '/^\/node_modules$/d' .gitignore
-        sed -i.bak -e '/^\/x$/d' .gitignore
+      - name: 🗃️ reconstitute node_modules for production
+        run: npm ci --omit=dev
 
-    - name: 🗃️ reconstitute node_modules for production
-      run: |
-        rm -rf node_modules
-        npm ci --omit=dev
+      - name: 🍞 moving files into x
+        run: |
+          mkdir -p x
+          mv node_modules x/node_modules
+          mv s x/s
+          mv assets x/assets
 
-    - name: 🗃️ copy files
-      run: |
-        rm -rf x/node_modules x/s
-        cp -r node_modules/ x/
-        cp -r s/ x/
+      - name: 📤 upload pages artifact
+        uses: actions/upload-pages-artifact@v3
+        with:
+          path: "x"
 
-    - name: 📝 configure pages
-      uses: actions/configure-pages@v2
-
-    - name: 📤 upload pages artifact
-      uses: actions/upload-pages-artifact@v3
-      with:
-        path: 'x'
-
-    - name: 🚀 deploy to github pages
-      id: deployment
-      uses: actions/deploy-pages@v4
+      - name: 🚀 deploy to github pages
+        id: deployment
+        uses: actions/deploy-pages@v4
